### ISSUE TITLE
Using the coraza.conf-recommended configutarion causes dangerous requests to show a warning instead of returning 403

### ISSUE THREAD

**Issue by WildHagai** [jptosso/coraza-caddy#2]
I've followed the README, and noticed that when using the 3 `include` statements in README causes dangerous request to show a warning in caddy's logs, but the request itself is executed as normal, without being blocked.
when using just the `include caddypath/coreruleset/rules/*.conf` - evereything is blocked, and a warning shows 

```
ModSecurity Core Rule Set is deployed without configuration! Please copy the crs-setup.conf.example template to crs-setup.conf, and include the crs-setup.conf file in your webserver configuration before including the CRS rules. See the INSTALL file in the CRS directory for detailed instructions
```
So I've included the `crs-setup.conf` and everything seems to work as expected, Is there something I'm missing, or perhaps the README should be updated?

**Comment by jptosso** [comment]
Hey @WildHagai, could you share yous Caddy configuration and logs? 

IT should look like this:

```
coraza_waf {
  include caddypath/coraza.conf-recommended
  include caddypath/coreruleset/crs-setup.conf.example
  include caddypath/coreruleset/rules/*.conf
}
```

Also, can you confirm you downloaded the Coraza default configurations? (caddypath/coraza.conf-recommended)

When you don't include the crs-setup.conf you will receive that message and your request will be blocked. Once you succeed with the configurations you may update your engine settings by setting ```SecRuleEngine On```

**Comment by WildHagai** [comment]
I guess that's what I missed, I thought `SecRuleEngine On` was already pre-configured. I didn't notice it was set on `DetectionOnly`

**Comment by jptosso** [comment]
Glad to help, feel free to send any feedback or report any other issue
