### ISSUE TITLE
High memory usage with CRS

### ISSUE THREAD

**Issue by abstractvector** [jptosso/coraza-caddy#4]
First, just want to say that I'm really excited about this project - it's great to have an alternative to Apache or nginx with ModSecurity!

I've built a distroless image that uses Caddy, Coraza and the Core Rule Set, based on the directions from your various repos. It took a little while to get things working correctly, but it is now - you can see it here: https://github.com/abstractvector/c3-waf

However, one thing I've noticed is that the memory consumption of the container is incredibly high when the CRS rules are loaded - jumping from ~10MB without the rules to ~200MB with the rules. The addition of these two lines is all it takes:

```yaml
include /coraza/coreruleset/crs-setup.conf
include /coraza/coreruleset/rules/*.conf
```

Once the container is loaded (e.g. using `ab`), the memory usage climbs significantly again. Stress testing the image without the CRS rules loaded will cause the memory usage to rise to ~20MB, but if I add the CRS rules in then memory consumption climbs to over 900MB!

This is easily reproduced using your `Dockerfile` (https://github.com/jptosso/coraza-waf-docker/blob/master/Dockerfile) and just adding in the relevant `crs-setup.conf` and `rules/*.conf` files as per the directions in your README.

Any idea what can be done to reduce the memory consumption? It doesn't appear to drop once the load has been removed.

**Comment by jptosso** [comment]
Hey @abstractvector thank you very much for the information and the test implementation, the memory footprint of the rules cannot be decreased a lot, but I will run some tests.

Regarding the transactions, maybe the GC is not fast enough to clear old transactions, I will run some experiments with a transaction.Close function to flush resources.

Can you provide me your hardware specs and the parameters used for AB? I will try to replicate the issue and create a detailed profiling.

**Comment by abstractvector** [comment]
My testing was crude and not particularly extensive, but the following command demonstrates the issue quite well:

```sh
$ ab -c 100 -n 10000 http://localhost:8000
```

Running this against either your Docker image with CRS compiled in or my Docker image linked above shows the situation quite clearly in contrast to the same test with the two CRS config file lines commented out. I'm just running this on a MacBook Pro - Docker has access to 4 CPUs and 2GB RAM.

Having now left it a while, it seems like the memory consumption does eventually drop - it looks like a minute or two after the `ab` run, the CPU usage for the process jumps to around 11-12% and the memory consumption begins dropping. I'm guessing that's the GC.

My hope is to turn this into a cross-platform build so it could run on a Raspberry Pi or similar, but that memory consumption is too high unfortunately.

**Comment by jptosso** [comment]
You are right about the memory spike but the GC turns down after a few seconds. It should be a priority to reduce the effort for the GC and proposals are more than welcome. I think I should create a function after tx.ProcessLogging(), something like tx.Close()

```go
func (tx *Transaction) Close() error {
  if tx.collections == nil {
    return fmt.Errorf("transaction already closed")
  tx.collections = nil
}
```

or manually clearing it:

```go
for k := range tx.collections {
    delete(tx.collections, k)
}
```

tx.collections is the heavier pointer for a transaction, forcing it's deletion should be enough.

**Comment by abstractvector** [comment]
I would love to help out, but I know very little about Go so I'm unlikely to be much assistance I'm afraid.

**Comment by jptosso** [comment]
It's cool, thank you for your discovery, I will close this issue once a solution is found, so you are kept posted.

**Comment by jptosso** [comment]
Hey @abstractvector, I have added a new cache feature for transactions so the memory is reused instead of freed and reallocated, your feedback on the branch would be really appreciated: https://github.com/jptosso/coraza-caddy/tree/tx_clean

Thank you
